# Thanks for using EnderPlus.
# For bug report or suggestion, join https://discord.gg/fV4P2yMSgR
# Use LuckPerms for permission
# Don't change Config.Version or plugin may break
# for Database, use a local file(Just type "enderplus.db") or use this "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false" on URL

Config:
  Update-Checker-Interval: 10 # In Minute.
  Online: true
  Version: ${project.version}

Database:
  Enable: false
  URL: "enderplus.db"
  User: "root"
  Password: ""


EnderChest:
  Name:
    row-1: "EnderChest-1"
    row-2: "EnderChest-2"
    row-3: "EnderChest-3"
    row-4: "EnderChest-4"
    row-5: "EnderChest-5"
    row-6: "EnderChest-6"
  Convert-onJoin: true
  Blacklist:
    -
    -
