# Thanks for usingDrop.
# For bug report or suggestion, join https://discord.gg/fV4P2yMSgR

# If Player.Require-Permission = true, player with "headdrop.player" permission will drop on death.
# Config.Require-Killer-Player = true means Killer need to be player to drop killed mob.
# If Config.Killer-Require-Permission = true, Player need "headdrop.killer" permission to let entity drop on death.
# Chances will be ignored if you disable drop.
# Chance is from 1-100. fraction number will not work.

# %killer% will return player name who killed the mob & %mob% will return mob name which was killed (only work on Bot section)

Config:
  Version: ${project.version}
  Update-Checker-Interval: 10 # In Minute.
  Require-Killer-Player: true
  Killer-Require-Permission: false
  Disable-Worlds:
    - demoWorld
    - demoWorld2


Bot:
  Enable: false
  WebHook: ""
  Title: "HeadDrop"
  Description: "%killer% killed %mob% and got a!"
  Footer: "HeadDrop by RRS"

PLAYER:
  Drop: true
  Chance: 100
  Require-Permission: false

ZOMBIE:
  Drop: true
  Chance: 100

WITHER_SKELETON:
  Drop: true
  Chance: 100

CREEPER:
  Drop: true
  Chance: 100

SKELETON:
  Drop: true
  Chance: 100

AXOLOTL:
  Name: "Axolotl"
  Drop: true
  Chance: 100

BAT:
  Name: "Bat"
  Drop: true
  Chance: 100

BEE:
  Name: "Bee"
  Drop: true
  Chance: 100

BLAZE:
  Name: "Blaze"
  Drop: true
  Chance: 100

CAT:
  Name: "Cat"
  Drop: true
  Chance: 100

DOLPHIN:
  Name: "Dolphin"
  Drop: true
  Chance: 100

DROWNED:
  Name: "Drowned"
  Drop: true
  Chance: 100

SPIDER:
  Name: "Spider"
  Drop: true
  Chance: 100

CAVE_SPIDER:
  Name: "Cave Spider"
  Drop: true
  Chance: 100

CHICKEN:
  Name: "Chicken"
  Drop: true
  Chance: 100

ENDERMAN:
  Name: "EnderMan"
  Drop: true
  Chance: 100

COW:
  Name: "Cow"
  Drop: true
  Chance: 100

ENDERMITE:
  Name: "EnderMite"
  Drop: true
  Chance: 100

EVOKER:
  Name: "Evoker"
  Drop: true
  Chance: 100

DONKEY:
  Name: "Donkey"
  Drop: true
  Chance: 100

FOX:
  Name: "Fox"
  Drop: true
  Chance: 100

SHEEP:
    Name: "Sheep"
    Drop: true
    Chance: 100

GIANT:
  Name: "Giant"
  Drop: true
  Chance: 100

HOGLIN:
  Name: "Hoglin"
  Drop: true
  Chance: 100

HUSK:
  Name: "Husk"
  Drop: true
  Chance: 100

GOAT:
  Name: "Goat"
  Drop: true
  Chance: 100

IRON_GOLEM:
  Name: "Iron Golem"
  Drop: true
  Chance: 100

ILLUSIONER:
  Name: "Illusioner"
  Drop: true
  Chance: 100

HORSE:
  Name: "Horse"
  Drop: true
  Chance: 100

GUARDIAN:
  Name: "Guardian"
  Drop: true
  Chance: 100

MUSHROOM_COW:
  Name: "Mushroom Cow"
  Drop: true
  Chance: 100

OCELOT:
  Name: "Ocelot"
  Drop: true
  Chance: 100

PHANTOM:
  Name: "Phantom"
  Drop: true
  Chance: 100

GLOW_SQUID:
  Name: "Glow Squid"
  Drop: true
  Chance: 100

PIG:
  Name: "Pig"
  Drop: true
  Chance: 100

LLAMA:
  Name: "LLAMA"
  Drop: true
  Chance: 100

MULE:
  Name: "Mule"
  Drop: true
  Chance: 100

PIGLIN:
  Name: "Piglin"
  Drop: true
  Chance: 100

PIGLIN_BRUTE:
  Name: "Piglin Brute"
  Drop: true
  Chance: 100

ELDER_GUARDIAN:
  Name: "Elder Guardian"
  Drop: true
  Chance: 100

PUFFERFISH:
  Name: "Puffer Fish"
  Drop: true
  Chance: 100

SILVERFISH:
  Name: "Silver Fish"
  Drop: true
  Chance: 100

POLAR_BEAR:
  Name: "Polar Bear"
  Drop: true
  Chance: 100

SALMON:
  Name: "Salmon"
  Drop: true
  Chance: 100

SHULKER:
  Name: "Shulker"
  Drop: true
  Chance: 100

STRAY:
  Name: "Stray"
  Drop: true
  Chance: 100

STRIDER:
  Name: "Strider"
  Drop: true
  Chance: 100

SKELETON_HORSE:
  Name: "Skeleton Horse"
  Drop: true
  Chance: 100

PILLAGER:
  Name: "Pillager"
  Drop: true
  Chance: 100

SQUID:
  Name: "Squid"
  Drop: true
  Chance: 100

WANDERING_TRADER:
  Name: "Wandering Trader"
  Drop: true
  Chance: 100

TURTLE:
  Name: "Turtle"
  Drop: true
  Chance: 100

SLIME:
  Name: "Slime"
  Drop: true
  Chance: 100

COD:
  Name: "Cod"
  Drop: true
  Chance: 100

RAVAGER:
  Name: "Ravager"
  Drop: true
  Chance: 100

WITCH:
  Name: "Witch"
  Drop: true
  Chance: 100

GHAST:
  Name: "Ghast"
  Drop: true
  Chance: 100

ZOMBIE_HORSE:
  Name: "Zombie Horse"
  Drop: true
  Chance: 100

WOLF:
  Name: "Wolf"
  Drop: true
  Chance: 100

VINDICATOR:
  Name: "Vindicator"
  Drop: true
  Chance: 100

ZOGLIN:
  Name: "Zoglin"
  Drop: true
  Chance: 100

TRADER_LLAMA:
  Name: "LLama"
  Drop: true
  Chance: 100

ZOMBIE_VILLAGER:
  Name: "Zombie Villager"
  Drop: true
  Chance: 100

WITHER:
  Name: "Witch"
  Drop: true
  Chance: 100

VILLAGER:
  Name: "Villager"
  Drop: true
  Chance: 100

PARROT:
  Name: "Parrot"
  Drop: true
  Chance: 100

TROPICAL_FISH:
  Name: "Tropical Fish"
  Drop: true
  Chance: 100

VEX:
  Name: "Vex"
  Drop: true
  Chance: 100

ZOMBIFIED_PIGLIN:
  Name: "Zombified Piglin"
  Drop: true
  Chance: 100

SNOW_GOLEM:
  Name: "Snow Golem"
  Drop: true
  Chance: 100

RABBIT:
  Name: "Rabbit"
  Drop: true
  Chance: 100

ALLAY:
  Name: "Allay"
  Drop: true
  Chance: 100

TADPOLE:
  Name: "Tadpole"
  Drop: true
  Chance: 100

FROG:
  Name: "Frog"
  Drop: true
  Chance: 100

WARDEN:
  Name: "Warden"
  Drop: true
  Chance: 100


