# Thanks for using EnderPlus.
# For bug report or suggestion, join https://discord.gg/fV4P2yMSgR
# Use luckperms for permission
# Don't change Config.Version or plugin will break
# If you choose this false, that means player will get normal Ender chest. but players can still get access to custom enderchest by /ec with right perm

Config:
  Enable: true
  Update-Checker: true
  Version: 2.0

Enderchest:
  Convert-onJoin: true