# Thanks for using EnderPlus.
# For bug report or suggestion, join https://discord.gg/fV4P2yMSgR
# Use luckperms for permission
# Don't change Config.Version or plugin will break

Config:
  Update-Checker: true
  Version: ${project.version}

Database:
  Enable: false
  Url: "localhost"
  Name: "enderplus"
  User: "root"
  Password: ""

EnderChest:
  Name: "EnderChest"
  Convert-onJoin: true